export const districtList = [
  'achham',
  'arghakhanchi',
  'baglung',
  'baitadi',
  'bajhang',
  'bajura',
  'banke',
  'bara',
  'bardiya',
  'bhaktapur',
  'bhojpur',
  'chitwan',
  'dadeldhura',
  'dailekh',
  'dang deukhuri',
  'darchula',
  'dhading',
  'dhankuta',
  'dhanusa',
  'dholkha',
  'dolpa',
  'doti',
  'gorkha',
  'gulmi',
  'humla',
  'ilam',
  'jajarkot',
  'jhapa',
  'jumla',
  'kailali',
  'kalikot',
  'kanchanpur',
  'kapilvastu',
  'kaski',
  'kathmandu',
  'kavrepalanchok',
  'khotang',
  'lalitpur',
  'lamjung',
  'mahottari',
  'makwanpur',
  'manang',
  'morang',
  'mugu',
  'mustang',
  'myagdi',
  'nawalparasi',
  'nuwakot',
  'okhaldhunga',
  'palpa',
  'panchthar',
  'parbat',
  'parsa',
  'pyuthan',
  'ramechhap',
  'rasuwa',
  'rautahat',
  'rolpa',
  'rukum',
  'rupandehi',
  'salyan',
  'sankhuwasabha',
  'saptari',
  'sarlahi',
  'sindhuli',
  'sindhupalchok',
  'siraha',
  'solukhumbu',
  'sunsari',
  'surkhet',
  'syangja',
  'tanahu',
  'taplejung',
  'terhathum',
  'udayapur',
];
export const bloodGroupList = ['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'];
export const distanceList = [
  { label: '5 KM', value: 5 },
  { label: '10 KM', value: 10 },
  { label: '25 KM', value: 25 },
  { label: '50 KM', value: 50 },
  { label: '100 KM', value: 100 },
  { label: '150 KM', value: 150 },
];
